// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urwmmtksrnaiepnkjjyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyd21tdGtzcm5haWVwbmtqanlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3ODUxNDMsImV4cCI6MjA2OTM2MTE0M30.-4j5gaRNP7J5hngbKMLusMkiA2ZEDHzSqXd8VJvl3O4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});